### ISSUE TITLE
Could not find a version that satisfies the requirement torch==1.1.0 (from -r requirements.txt (line 4))

### ISSUE THREAD

**Issue by Jimmy2027** [MonsieurWave/PerfusionCT-Net#3]
Trying to install the requirements with `pip install -r requirements.txt` in a venv with python >3.7 gives me the error "Could not find a version that satisfies the requirement torch==1.1.0 (from -r requirements.txt (line 4))".
Downgrading to python 3.7 solves that issue.

**Comment by JulianKlug** [comment]
This can easily be achieved with conda:
`conda create -n "pctnet" python=3.7`

Another reason for this error could be that you already have another version of torch installed in your environment.
